# Server
server:
  port: 8001
  servlet:
    context-path: /api
  tomcat:
    accesslog:
      enabled: true
      directory: /var/log/publisher/tomcat
    connection-timeout: 30s

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  # RabbitMQ connection properties
  rabbitmq:
    host: localhost
    port: 5672
    username: mmr.rmq.user
    password: Pa55word

# RabbitMQ queue properties
stream:
  csv:
    exchange: mmr.exchange.filedata
    routing: mmr.routing.key

# Logging
logging:
  level:
    root: INFO
    org:
      apache:
        tomcat: error
        catalina: error
      springframework: ERROR
      hibernate: ERROR

